version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      generated-data:
        patterns:
          - linguist-languages
          - material-icon-theme
