export const VSCODE_IDS = {
  "C#": "csharp",
  "C++": "cpp",
  "Go Module": "go.mod",
  "Ignore List": "ignore",
  "JSON with Comments": "jsonc",
  "Objective-C++": "objective-cpp",
  "Protocol Buffer": "proto3",
  "Visual Basic .NET": "vb",
  "Vim script": "vim",
  SVG: "xml",
  "F#": "fsharp",
  "Java Properties": "properties",
  Pug: "jade",
  TeX: "latex",
  Batchfile: "bat",
  Shell: "shellscript",
  TSX: "typescriptreact",
  Text: "plaintext",
};

export const PREFERRED_EXTENSIONS = {
  as: "ActionScript",
  cfg: "INI",
  cs: "C#",
  ex: "Elixir",
  h: "C",
  html: "HTML",
  json: "JSON",
  m: "Objective-C",
  md: "Markdown",
  mod: "Go Module",
  php: "PHP",
  pl: "Perl",
  r: "R",
  rs: "Rust",
  sql: "SQL",
  ts: "TypeScript",
  tsx: "TSX",
  txt: "Text",
  v: "Verilog",
  yaml: "YAML",
  yml: "YAML",
};

export const EXTENSION_IDS = {
  jsx: "javascriptreact",
  tf: "terraform",
  tfvars: "terraform-vars",
};
